name: domain
description: The domain layer of the application.

version: 1.0.0+1

publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  codenic_bloc_use_case: ^3.0.0-dev2
  codenic_exception_converter: ^1.0.0-dev9

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  module:
    androidX: true
    androidPackage: com.example.domain
    iosBundleIdentifier: com.example.domain