name: note_app
description: The root module of the application.

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  presentation:
    path: modules/presentation

  domain:
    path: modules/domain
    
  infrastructure:
    path: modules/infrastructure
  
dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
