name: codenic_bloc_use_case
description: A suite of abstract cubits to reduce boilerplate code and construct app use cases.
version: 3.0.2
repository: https://github.com/CodenicCoders/codenic_clean_arch/tree/main/packages/codenic_bloc_use_case
issue_tracker: https://github.com/CodenicCoders/codenic_clean_arch/issues
homepage: https://arch.codenic.dev
documentation: https://arch.codenic.dev/packages/codenic-bloc-use-case

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  fpdart: ^0.4.0
  meta: ^1.9.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.0
  test: ^1.22.2
  very_good_analysis: ^3.1.0
