name: codenic_bloc_use_case
description: A suite of abstract cubits to reduce boilerplate code and construct app use cases.
version: 5.0.0
repository: https://github.com/CodenicCoders/codenic_clean_arch/tree/main/packages/codenic_bloc_use_case
issue_tracker: https://github.com/CodenicCoders/codenic_clean_arch/issues
homepage: https://arch.codenic.dev
documentation: https://arch.codenic.dev/packages/codenic-bloc-use-case

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  fpdart: ^0.6.0
  meta: ^1.9.1

dev_dependencies:
  bloc_test: ^9.1.1
  test: ^1.24.3
  very_good_analysis: ^5.0.0
