name: codenic_exception_converter

on:
  push:
    paths:
      - "packages/codenic_exception_converter/**"
      - ".github/workflows/codencodenic_exception_converteric_logger.yaml"

  pull_request:
    paths:
      - "packages/codenic_exception_converter/**"
      - ".github/workflows/codenic_exception_converter.yaml"
    
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: packages/codenic_exception_converter

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0

      - name: Install Dependencies
        run: dart pub get
      
      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: packages/codenic_exception_converter/coverage/lcov.info
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: codenic_exception_converter
          token: ${{ secrets.CODECOV_TOKEN }}

  pana:
    defaults:
      run:
        working-directory: packages/codenic_exception_converter
        
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0

      - name: Install Dependencies
        run: |
          flutter packages get
          flutter pub global activate pana
          
      - name: Verify Pub Score
        run: ../../tool/verify_pub_score.sh
